### ISSUE TITLE
Correct handling of crate version in workspace.

### ISSUE THREAD

**Issue by Jisu-Woniu** [kellpossible/cargo-i18n#118]
I ran `cargo i18n` in my project directory and got this error:

```plaintext
Error: Cannot parse Cargo configuration file "./Cargo.toml" because Cargo.toml's package version needs to be a string..
```

and my `Cargo.toml` is like:

```toml
[workspace]
members = [
# sub-crates
]

[workspace.package]
version = "0.1.0"
# other global configurations

[package]
version.workspace = true
```

As is mentioned in [The Cargo Book](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table), the version of the root crate should be inherited from the `workspace.package` region (in this case, `0.1.0`).
