### ISSUE TITLE
Using wasm target gives error: Error resolving module specifier “env”. Relative module specifiers must start with “./”, “../” or “/”.

### ISSUE THREAD

**Issue by johansmitsnl** [kellpossible/cargo-i18n#70]
When I load the `i18n_embed::select` it gives me this error with a wasm target.

```toml
i18n-embed = { version = "0.12", features = ["fluent-system", "web-sys-requester"] }
rust-embed = { version = "5", features = ["debug-embed"] }
```

```rust
// lib.rs

use i18n_embed::{
    WebLanguageRequester,
};
use rust_embed::RustEmbed;

use i18n_embed::fluent::{FluentLanguageLoader, fluent_language_loader};

#[derive(RustEmbed)]
#[folder = "i18n"] // path to the compiled localization resources
struct Localizations;

#[wasm_bindgen(start)]
pub fn main() {
  let language_loader: FluentLanguageLoader = fluent_language_loader!();
  let requested_languages = WebLanguageRequester::requested_languages();
  let _result = i18n_embed::select(&language_loader, &Localizations, &requested_languages);
}
```

```toml
# i18n.toml

fallback_language = "en"

[fluent]
assets_dir = "i18n"
```

```ftl
# i18n/en/frontend.ftl

logout = Logout translated
```

On the browser console a error message from WASM: `Uncaught TypeError: Error resolving module specifier “env”. Relative module specifiers must start with “./”, “../” or “/”.`
