### ISSUE TITLE
Error when using workspace-defined package metadata.

### ISSUE THREAD

**Issue by m00nwtchr** [kellpossible/cargo-i18n#97]
IE: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacepackage-table
Specifically:
```
error: proc macro panicked
   --> XXXX/app/src/i18n.rs:31:9
    |
31  |         i18n_embed_fl::fl!($crate::i18n::LANGUAGE_LOADER, $message_id)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: XXXX/app/src/view/XXXXXX.rs:275:26
    |
275 |                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    |                          ------------------ in this macro invocation
    |
    = help: message: Error parsing Cargo.toml: InvalidManifest("`version` in [package] section is not a string")
    = note: this error originates in the macro `fll` (in Nightly builds, run with -Z macro-backtrace for more info
```
```toml
[package]
name = "XXXX"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
```
Changing version to `version = "1.0.0"` fixes it.
